# Generated by Django 5.1 on 2024-08-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Room',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='appchat.role')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='appchat.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
